name: "Benchmarking"
on:
  workflow_dispatch:
  push:
    paths:
      - 'api/src/benchmark/kotlin/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest, ubuntu-18.04, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Running the tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: benchmark