name: "Benchmarking"
on:
  workflow_dispatch:
  schedule:
    # Run at 04:05 every Wednesday.
    - cron: '5 4 * * 3'
  pull_request:
    paths:
      - 'api/benchmark/kotlin/**'
  push:
    branches:
      - main
    paths:
      - 'api/benchmark/kotlin/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest, ubuntu-18.04, macos-10.15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Running the tests
        uses: gradle/gradle-build-action@v1
        with:
          arguments: benchmark