name: "Checks and Tests"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Clean project
        uses: gradle/gradle-build-action@v2
        with:
          distributions-cache-enabled: true
          configuration-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: clean

      - name: Check project specification
        uses: gradle/gradle-build-action@v2
        with:
          # See: https://docs.gradle.org/current/userguide/java_testing.html#sec:test_execution
          arguments: |
            apiCheck
            spotlessCheck
            -PignoreFailures=true
            --scan

      - name: Test all cases
        uses: gradle/gradle-build-action@v2
        with:
          # See: https://docs.gradle.org/current/userguide/java_testing.html#sec:test_execution
          arguments: |
            test
            -PignoreFailures=true
            --stacktrace
            --scan

  full-check:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Clean project
        uses: gradle/gradle-build-action@v2
        with:
          distributions-cache-enabled: true
          configuration-cache-enabled: true
          dependencies-cache-enabled: true
          arguments: clean

      - name: Check project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check -x built-ins:generator:lint
