name: Gradle wrapper update

on:
  schedule:
    - cron: '5 20 * * *'
  push:
    paths:
      # Also run when this workflow configuration changes
      - .github/workflows/gradle-wrapper-update.yml

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Update gradle wrapper version
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          labels: versions, gradle-wrapper
          reviewers: RinOrz
